// src/bindings.cpp

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <google/protobuf/message.h>
#include "egm.pb.h"         // Generated by Google Protocol Buffer compiler protoc
#include "egm_wrapper.pb.h" // Generated by Google Protocol Buffer compiler protoc
#include "pybind11_protobuf/native_proto_caster.h"

namespace py = pybind11;

// Forward declarations of binding functions
void bind_common(py::module& m);
void bind_controller(py::module& m);
void bind_udp(py::module& m);

PYBIND11_MODULE(_abb_libegm, m) {
    m.doc() = "Python bindings for ABB LibEGM - External Guided Motion interface";

    GOOGLE_PROTOBUF_VERIFY_VERSION;

    pybind11_protobuf::ImportNativeProtoCasters();

    // Initialize the submodules
    bind_common(m);
    bind_controller(m);
    bind_udp(m);
    atexit(google::protobuf::ShutdownProtobufLibrary);
}